test_configuration:
  - target: PrefireExample
  - simulator_device: "iPhone17,1"
  - required_os: 18
  - snapshot_devices:
      - iPhone 15
      - iPad
  - imports:
      - UIKit
      - Foundation
  - use_grouped_snapshots: false
  - record_in_dark_mode: true

playbook_configuration:
  - imports:
      - UIKit
      - Foundation
