test_configuration:
  - target: PrefireExample
  - simulator_device: "iPhone15,2"
  - required_os: 17
  - snapshot_devices:
      - iPhone 15
      - iPad
  - imports:
      - UIKit
      - Foundation

playbook_configuration:
  - imports:
      - UIKit
      - Foundation
