configurations:
  # Preview ViewModels
  - sources:
      - ${TARGET_DIR}/
    templates:
      - ${TEMPLATES_DIR}/AutoMockable.stencil
    output: ${DERIVED_DATA_DIR}/PreviewViewModels.generated.swift
    args:
      autoMockableImports:
        - AVFoundation
        - Combine
        - PhotosUI
        - SellerConfiguration
        - SellerInterfaces
        - SellerUtils
        - SellerUI
        - SwiftUI
        - SellerUIKit

    -

  # Equatable
  - sources:
      - ${TARGET_DIR}/
    templates:
      - ${TEMPLATES_DIR}/AutoEquatable.stencil
    output: ${DERIVED_DATA_DIR}/Equatable.generated.swift
