test_configuration:
  - target: PrefireExample
  - simulator_device: "iPhone17,1"
  - required_os: 18
  - snapshot_devices:
      - iPhone 15
      - iPad
      - Mac
  - imports:
      - UIKit
      - Foundation

playbook_configuration:
  - imports:
      - UIKit
      - Foundation
