test_configuration:
  - target: PrefireExample
  - simulator_device: "AppleTV5,3"
  - required_os: 18
  - snapshot_devices:
      - Apple TV
  - imports:
      - UIKit
      - Foundation

playbook_configuration:
  - imports:
      - UIKit
      - Foundation
