#!/bin/sh

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -r|--root) root="$2"; shift ;;
        --sourcery) sourcery="$2"; shift ;;
        -o|--output) output="$2"; shift ;;
        --target) target="$2"; shift ;;
        --sources) sources="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

PREFIRE_DEFAULT=${BUILD_DIR%Build/*}SourcePackages/checkouts/PreFire
SOURCERY_DEFAULT="/opt/homebrew/bin/sourcery"

PREFIRE_ROOT="${root:-$PREFIRE_DEFAULT}"
SOURCERY_ROOT="${sourcery:-$SOURCERY_DEFAULT}"
TEMPLATES_ROOT=$PREFIRE_ROOT/Sources/PreFire/Templates


if [[ -n "{$target}" ]]; then
    $SOURCERY_ROOT \
    --sources $sources \
    --templates $TEMPLATES_ROOT/PreviewModels.stencil \
    --output $output

else
    $SOURCERY_ROOT \
    --sources $sources \
    --templates $TEMPLATES_ROOT/PreviewModels.stencil \
    --output $output \
    --args mainTarget=$target
fi
