#!/bin/sh

if [[ "$1" == "playbook" ]]; then
    is_playbook=true
elif [[ "$1" == "tests" ]]; then
    is_tests=true
else
    echo "error: Prefire: Command-line pasing error"
    exit 1
fi

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --sourcery) sourcery="$2"; shift ;;
        -r|--root) root="$2"; shift ;;
        -o|--output) output="$2"; shift ;;
        -t|--target) target="$2"; shift ;;
        -s|--sources) sources="$2"; shift ;;
    esac
    shift
done

PREFIRE_DEFAULT=${BUILD_DIR%Build/*}SourcePackages/checkouts/PreFire
SOURCERY_DEFAULT="/opt/homebrew/bin/sourcery"

PREFIRE_ROOT="${root:-$PREFIRE_DEFAULT}"
SOURCERY_ROOT="${sourcery:-$SOURCERY_DEFAULT}"
TEMPLATES_ROOT=$PREFIRE_ROOT/Sources/PreFire/Templates

if [[ $is_playbook ]]; then
    TEMPLATE=$TEMPLATES_ROOT/PreviewModels.stencil
elif [[ $is_tests ]]; then
    TEMPLATE=$TEMPLATES_ROOT/PreviewTests.stencil
fi


if [[ -z "$target" ]]; then
    $SOURCERY_ROOT \
    --sources $sources \
    --templates $TEMPLATE \
    --output $output
else
    $SOURCERY_ROOT \
    --sources $sources \
    --templates $TEMPLATE \
    --output $output \
    --args mainTarget=$target
fi
