name: Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build (branch, tag or SHA)'
        required: false
        default: 'master'
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create Release
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create achrive
        run: make archive
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: prefire.tar.gz

  update-homebrew:
    needs: release
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: upgrade-brew-tap
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: Prefire
          homebrew-tap: barredewe/homebrew-prefire
          tag-name: ${{ github.ref_name }}
          download-url: "https://github.com/barredewe/prefire/releases/download/${{ github.ref_name }}/prefire.tar.gz"
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}